testing workflow

diff --git a/.github/workflows/tf-plan.yml b/.github/workflows/tf-plan.yml
--- a/.github/workflows/tf-plan.yml
+++ b/.github/workflows/tf-plan.yml
@@ -56,18 +56,19 @@ jobs:
 
     - name: Terraform Plan
       id: tf-plan
-      run: |
-        export exitcode=0
-        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+      run: terraform plan
+      # run: |
+      #   export exitcode=0
+      #   terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
 
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+      #   echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
         
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else 
-          exit 0
-        fi
+      #   if [ $exitcode -eq 1 ]; then
+      #     echo Terraform Plan Failed!
+      #     exit 1
+      #   else 
+      #     exit 0
+      #   fi
         
     # Save plan to artifacts  
     - name: Publish Terraform Plan
